version: "3.9"
services:
  db:
    image: 'postgres:14.5-alpine3.16'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: project2-event-planning
    volumes:
      - ./db-data/:/var/lib/postgresql/data/:rw